# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scripts/ufms.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12scripts/ufms.proto\x12\x04UFMS\"\x87\x02\n\x0b\x42usWayPoint\x12\x0f\n\x07vehicle\x18\x01 \x01(\t\x12\x0e\n\x06\x64river\x18\x02 \x01(\t\x12\r\n\x05speed\x18\x03 \x01(\x02\x12\x10\n\x08\x64\x61tetime\x18\x04 \x01(\x03\x12\t\n\x01x\x18\x05 \x01(\x01\x12\t\n\x01y\x18\x06 \x01(\x01\x12\t\n\x01z\x18\x07 \x01(\x02\x12\x0f\n\x07heading\x18\x08 \x01(\x02\x12\x10\n\x08ignition\x18\t \x01(\x08\x12\x0e\n\x06\x61ircon\x18\n \x01(\x08\x12\x0f\n\x07\x64oor_up\x18\x0b \x01(\x08\x12\x11\n\tdoor_down\x18\x0c \x01(\x08\x12\x0b\n\x03sos\x18\r \x01(\x08\x12\x0f\n\x07working\x18\x0e \x01(\x08\x12\x0f\n\x07\x61nalog1\x18\x0f \x01(\x02\x12\x0f\n\x07\x61nalog2\x18\x10 \x01(\x02\"d\n\x0b\x42\x61seMessage\x12\x1e\n\x07msgType\x18\x01 \x01(\x0e\x32\r.UFMS.MsgType\x12*\n\rbus_way_point\x18\x02 \x01(\x0b\x32\x11.UFMS.BusWayPointH\x00\x42\t\n\x07payload*8\n\x07MsgType\x12\x11\n\rMSG_TYPE_ZERO\x10\x00\x12\x1a\n\x16MSG_TYPE_BUS_WAY_POINT\x10\x66\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scripts.ufms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSGTYPE']._serialized_start=396
  _globals['_MSGTYPE']._serialized_end=452
  _globals['_BUSWAYPOINT']._serialized_start=29
  _globals['_BUSWAYPOINT']._serialized_end=292
  _globals['_BASEMESSAGE']._serialized_start=294
  _globals['_BASEMESSAGE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
